# Generated by Django 4.0.3 on 2022-04-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('admin_permisions', 'Admin Permission'), ('user_prmission', 'User Permission')]},
        ),
    ]
