# Generated by Django 4.0.3 on 2022-04-12 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('occupaid', models.BooleanField()),
                ('caregory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.subcategory')),
            ],
        ),
    ]
