# Generated by Django 4.0.3 on 2022-04-12 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0004_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'permissions': [('admin_permisions', 'Admin Permission'), ('user_prmission', 'User Permission')]},
        ),
    ]
