# Generated by Django 4.0.3 on 2022-04-13 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room_management', '0007_lineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('starting_date', models.DateTimeField()),
                ('ending_Date', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_management.rooms')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
