# Generated by Django 4.0.3 on 2022-04-14 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0008_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='room_number_id_id',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='room_numb',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='room_management.rooms'),
            preserve_default=False,
        ),
    ]
