# Generated by Django 4.0.3 on 2022-04-15 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_management', '0009_remove_lineitem_room_number_id_id_lineitem_room_numb'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='order_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='room_management.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitem', to='room_management.order'),
        ),
    ]
